# Generated by Django 6.0.7 on 2026-07-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos_fotos/')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dia_vencimento', models.IntegerField()),
                ('pago_este_mes', models.BooleanField(default=False)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
