# Generated by Django 6.0.7 on 2026-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.CharField(choices=[('MWF_17', 'Seg/Qua/Sex - 17:00 às 18:00 (R$ 120)'), ('MWF_18', 'Seg/Qua/Sex - 18:00 às 19:00 (R$ 120)'), ('MWF_19', 'Seg/Qua/Sex - 19:00 às 20:00 (R$ 120)'), ('MWF_20', 'Seg/Qua/Sex - 20:00 às 21:00 (R$ 120)'), ('TR_19', 'Ter/Qui - 19:00 às 20:00 (R$ 100)'), ('TR_20', 'Ter/Qui - 20:00 às 21:00 (R$ 100)')], default='MWF_19', max_length=10),
        ),
    ]
