# Generated by Django 6.0.7 on 2026-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='pago_este_mes',
        ),
        migrations.AddField(
            model_name='aluno',
            name='ultimo_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
